on:
  issues: 
    types: [labeled, unlabeled]
  workflow_dispatch:
    inputs:
      issue:
        description: 'Issue number to work with'
        required: true
        default: '11'
    
    
jobs:
  find-action-name:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'security-check'

    env:
      body: ${{ github.event.issue.body }}

    outputs:
      action: ${{ steps.get-action.outputs.action }}
      owner: ${{ steps.get-action.outputs.owner }}
      name: ${{ steps.get-action.outputs.name }}
      request_owner: ${{ steps.get-action.outputs.request_owner }}
      request_repo: ${{ steps.get-action.outputs.request_repo }}
      request_issue: ${{ steps.get-action.outputs.request_issue }}

    steps:
    - uses: actions/checkout@v2
    - id: dispatch_issue_find
      run: |
         echo "Testing for dispatch event with issue number: ${{ github.event.inputs.issue }}"
         issue_number=${{ github.event.inputs.issue }}
         if [ "${{ github.event.inputs.issue }}" == "" ]; then
           echo "issue number not found in workflow dispatch event"
           echo 'Found the issue that triggered this event with number [${{ github.event.issue.number }}]'
           echo 'Found the issue title [${{ github.event.issue.title }}]'
         else
           echo "issue number found: [$issue_number]"
           # output a fixed variable
           echo "::set-output name=issue_number::${issue_number}"
         fi
         
         echo -e $body

    - uses: actions/github-script@v5
      name: Find action from comment
      id: get-action
      with:
        result-encoding: string
        script: |
          const script = require('./src/find-action-from-comment.js')
                  
          // note: owner is now the organization the FORK lives in:
          const owner = context.repo.owner
          const repo = context.repo.repo
          let issue_number = context.issue.number         
          
          if (issue_number == null) {
            // try to load issue number from other step:
            console.log(`issue number not found in context, searching for it in workflow dispatch step`)
            console.log(`issue number: [${{ steps.dispatch_issue_find.outputs.issue_number }}]`)
            issue_number = `${{ steps.dispatch_issue_find.outputs.issue_number }}`
          }

          console.log(await script({github, owner, repo, issue_number}))
    
  check-action-security-setup:
    runs-on: ubuntu-latest
    needs: find-action-name
    steps:
    - name: Check-out referenced Action
      run: |
        git clone https://github.com/${{ needs.find-action-name.outputs.action }} action
        
    - name: Check CodeQL step in Workflow
      id: has-codeql-in-workflow
      run: |
        echo "Looking for CodeQL action in any Workflow of the action"
        if [ ! -d "action/.github/workflows" ]; then
          jq -nc '{"body": "⛔️ No workflows found"}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
        else
          if [ `grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/init' | wc -l` -gt 0 ]; then
            WORKFLOW=`grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/init' -H | cut -f1 -d' ' | sed "s/:$//g"`
            jq -nc "{\"body\": \"✅ CodeQL Init step found in $WORKFLOW\"}" | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
          else
            jq -nc '{"body": "⛔️ No CodeQL Init step found"}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
          fi

          if [ `grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/analyze' | wc -l` -gt 0 ]; then
            WORKFLOW=`grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/analyze' -H | cut -f1 -d' ' | sed "s/:$//g"`
            jq -nc "{\"body\": \"✅ CodeQL Analyze step found in $WORKFLOW\"}" | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
          else
            jq -nc '{"body": "⛔️ No CodeQL Analyze step found"}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
          fi
        fi
    
    - name: Scan docker container when present
      id: scan-docker-container-when-present
      run: |
        #!/bin/bash

        set -ueo pipefail

        if [ "docker" != `yq e '.runs.using' action/action.yml` ] ; then
          jq -nc '{"body": "Action is not using a Docker image"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
                    
          exit 0
        fi

        echo "Installing trivy"
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

        if [ "Dockerfile" == `yq e '.runs.image' action/action.yml` ]; then
          echo "Scan docker image with trivy"
          docker build -t action-checkout/${{ needs.find-action-name.outputs.action }} action/
          trivy --quiet image action-checkout/${{ needs.find-action-name.outputs.action }} > issues
          docker image rm action-checkout/${{ needs.find-action-name.outputs.action }}
        else
          echo "Scan docker image with trivy"
          trivy --quiet image $IMAGE > issues
        fi

        # Check if LOW or MEDIUM issues are found
        if [ `cat issues | grep -e LOW -e MEDIUM | wc -l` -gt 1 ] ; then
          jq -nc '{"body": "⚠️ Docker image scanning found LOW or MEDIUM issues. Please check the logs."}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
        fi

        # Check if HIGH or CRITICAL issues are found
        if [ `cat issues | grep -e HIGH -e CRITICAL | wc -l` -gt 1 ] ; then
          jq -nc '{"body": "⛔ Docker image scanning found HIGH or CRITICAL issues. Please check the logs."}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ needs.find-action-name.outputs.request_owner }}/${{ needs.find-action-name.outputs.request_repo }}/issues/${{ needs.find-action-name.outputs.request_issue }}/comments"
            
            exit 17
        fi

    - name: Get result for verification
      run: |
        echo "Owner: ${{needs.find-action-name.outputs.owner}}"
        echo "Name: ${{needs.find-action-name.outputs.name}}"

    # todo: add a new comment to the issue indication the action of forking the repo over to the other org?

  fork-action-test:
    runs-on: ubuntu-latest
    needs: find-action-name
    steps:
    - uses: actions/checkout@v2

    - name: Fork the action repository to sahithi-org
      uses: rajbos-actions/forker@v0.0.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        repo: ${{needs.find-action-name.outputs.name}}
        owner: ${{needs.find-action-name.outputs.owner}}
        org: sahithi-org

    # since dependabot alerts and dependency graph is enabled on the organization level, we only need to add a CodeQL setup
    # for it we need to inject the default CodeQL config into the forked action repository
    - uses: actions/github-script@v5
      name: Inject CodeQL workflow into new forked repository
      # todo: clear all other workflows first
      id: CodeQL
      env:
        repo: ${{needs.find-action-name.outputs.name}}
        org: sahithi-org # todo: make central parameter
      with:      
        github-token: ${{ secrets.GH_TOKEN }}  
        script: |            
            const { repo, org } = process.env
            console.log(`Looking at this repository: [${org}/${repo}]`)
            
            const { readFileSync } = require('fs')
            const path = 'codeql-analysis.yml'
            const content = readFileSync(`${process.env.GITHUB_WORKSPACE}/${path}`)
            
            const targetPath = ".github/workflows/codeql-analysis.yml"
            console.log(`Checking to see if [${targetPath}] already exists in the forked repo`)
            
            // this call gives a 404, since the file does not exist, how to handle this?
            let data
            try {
               console.log(`before the call`)
               let { data } = await github.rest.repos.getContent({ 
                owner: org,
                repo,
                path: ".github/workflows/codeql-analysis.yml"  // todo: use variable here
              })
              console.log(`after the call`)
              console.log(`data:`)
              console.log(data)
              
              console.log(`data.content:`)
              console.log(data.content)
            }
            catch (e) {
              console.log(`in the catch with e:`)
              console.log(e)
            }
            console.log(`after the catch`)
            
            let content2
            if (data === undefined || data.content === undefined) {
              console.log('data is null, so workflow does not exist yet')
              content2 = content
            } else {
              console.log('data is not null, so does exist? We need to compare their hashes to see if we need to overwrite')
              content2 = Buffer.from(data.content.toString('base64'), 'base64')
              if (Buffer.from(data.content, 'base64').compare(content2) === 0) {
                console.log('data in the codeql workflow file is the same. Halting execution')
                return
              }
            }
                        
            console.log(`Uploading the CodeQL workflow to the forked repository`)
            github.rest.repos.createOrUpdateFileContents({
              owner: org,
              repo,
              path: targetPath,
              message: "Adding CodeQL setup",
              content: content2.toString('base64'),
              sha: data === undefined ? null : data.sha
            })
            console.log('CodeQL workflow uploaded')
            // todo: find the CodeQL workflow execution and wait for it to complete
            // todo: handle the result of the workflow execution: what if all languages fail?
            // todo: read the results from the CodeQL workflow
            // todo: generate random cron schedule?
  
